// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/xeventa/base-service/core/contract"
	"github.com/xeventa/base-service/core/db"
	"github.com/xeventa/base-service/core/environment"
	"github.com/xeventa/base-service/src/public"
)

// Injectors from injector.go:

func InjectAppConfig() (*environment.Config, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	return config, nil
}

func InjectLogger() (*environment.Config, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	return config, nil
}

func InjectMySQL() (*db.MySQL, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	mySQL := ProvideMySQL(config)
	return mySQL, nil
}

func InjectRoutes() ([]contract.IRoute, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	service := public.NewService(config)
	delivery := public.NewDelivery(service)
	route := public.NewRoute(delivery)
	v := ProvideRoutes(route)
	return v, nil
}

// injector.go:

var (
	AppModule = wire.NewSet(
		ProvideConfig,
		ProvideLogger,
		ProvideMySQL,
	)
)
